xetdata/xet-core

rust/gitxetcore/src/command/merkledb.rs
rust/gitxetcore/src/command/summary.rs
rust/gitxetcore/src/utils.rs

Implement two commands to merge git notes for merging PRs across repos.
Fix https://github.com/xetdata/xethub/issues/3475, fix https://github.com/xetdata/xethub/issues/2345, fix https://github.com/xetdata/xethub/issues/3509

Merge git notes across repos commands

---

rust/gitxetcore/src/data_processing_v2.rs
rust/merkledb/src/aggregate_hashes.rs

Dedup against previous chunks in the same CAS block, preventing a sequence of identical chunks to fill up a CAS block and cause lookup table irregularities.

Allows dedup against previous chunks within the same CAS block on clean.

---

rust/gitxetcore/src/xetmnt/watch/watcher.rs

VSCode shows test code warnings as compile errors, which is slightly annoying.   Quick fix.

Fixed code warnings in test (annoying in vscode)

---

rust/cache/src/xorb_cache.rs
rust/gitxetcore/src/summaries_plumb.rs
rust/gitxetcore/src/xetmnt/watch/metadata.rs
rust/gitxetcore/src/xetmnt/watch/metadata/cache.rs
rust/gitxetcore/src/xetmnt/watch/metadata/filesystem.rs
rust/gitxetcore/src/xetmnt/watch/metadata/symbol.rs
rust/parutils/src/parallel_utils.rs
rust/s3/src/client.rs

Currently, there were a handful of files (many quite old) in which cargo fmt was not fully run, and I ended up having issues with this in an unrelated PR.  This PR cleans up all these issues in one go. 
There are no code changes outside of whitespace and formatting.

Run cargo fmt on repo

---

rust/gitxetcore/src/command.rs

With the gitxetcore seperation, the command parsing is in gitxetcore which affects the name of the program printed by git-xet -V making it print "gitxetcore" instead.
This forces the name to "git-xet" instead of "gitxetcore"

Fix git-xet --version

---

rust/gitxetcore/src/command/mount.rs
rust/gitxetcore/src/constants.rs
rust/gitxetcore/src/smudge_query_interface.rs
rust/gitxetcore/src/xetmnt/mod.rs
rust/mdb_shard/src/shard_file_reconstructor.rs

This reduces llama2 mount time from a couple of minutes on my home internet to 3.5s.
- Do not download shards on MDBv2 repos.
- Cache reconstruction lookups
- some documentation
- removed a misleading printout with number of objects / bytes (since the NFS is now lazily constructed... we do not actually have this number.)
Note that further optimizations like directly using the xetblob interface rather than the git methods, can reduce this to instant.

MDBv2 Mount optimizations

---

rust/cas_client/src/data_transport.rs
rust/cas_client/src/grpc.rs
rust/cas_client/src/remote_client.rs

Fix Internal #3588 and #3496
Avoid lots of spurious printouts that are actually ok.

Downgrade several CAS Client warn to info and error to warn

---

rust/gitxetcore/src/command/mount.rs

It is difficult to reliably identify the location of the python binary which was used to run the 'xet' command. This is required to "relaunch" xet as a daemon. Here, instead we directly relaunch the 'xet' command directly, hoping that the system will "do the right thing" (i.e. exec the script with the shebang command at the start of 'xet').

Potential fix for wrong Python binary detection

---

rust/gitxetcore/src/merkledb_shard_plumb.rs

The endpoint for a local cas is http://localhost:4000. Adding the condition to check for "localhost" so local cas doesn't try to talk to DynamoDB.

localhost cas skips register shard 

---

rust/mdb_shard/src/utils.rs

On windows, paths do not use / as the separator, but \.  This fixes a bug in which shard paths with \ are not parsed correctly.

Path slash issue

---

rust/xetblob/src/xet_repo.rs

While we're still figuring this out, the "Synchronize with remote" step is now enabled only if the environment variable XET_FETCH_ALL_SHARDS is set.  If this is not set, then this step is skipped, and all dedup relies on the shard hints mechanism.  However, this may have unforeseen consequences, so for now it may still be enabled for debugging and profiling.

begin_write_transaction now lets the synchronize step be optional.

---

rust/gitxetcore/src/data_processing_v1.rs
rust/gitxetcore/src/data_processing_v2.rs

Fix https://github.com/xetdata/xethub/issues/2421
```
di@di-mbp ~/tt/bb % git init && git xet init -m1 -f && git add .
Initialized empty Git repository in /Users/di/tt/bb/.git/
git-xet 0.11.2 filter started
Xet: Deduplicating data blocks: 123.05 MiB | 15.38 MiB/s, done.
123.05 MiB added, stored 123.05 MiB (0.0% reduction)
```
```
di@di-mbp ~/tt/bb % git init && git xet init -m2 -f && git add .
Initialized empty Git repository in /Users/di/tt/bb/.git/
git-xet 0.11.2 filter started
Xet: Deduplicating data blocks: 123.05 MiB | 15.38 MiB/s, done.
123.05 MiB added, stored 123.05 MiB (0.0% reduction)
```

Better dedup ratio message

---

rust/mdb_shard/src/utils.rs

I'm not sure why the previous was failing, as the given pattern would have matched the regex in question.  However, this relies on the underlying file path library, so it should be more robust on windows.

Possible fix for https://github.com/xetdata/xethub/issues/3890.

---

rust/gitxetcore/src/command/login.rs
rust/gitxetcore/src/config/cas.rs
rust/gitxetcore/src/config/xet.rs
rust/xet_config/src/cfg.rs
rust/xet_config/src/loader.rs

This fixes an issue in which XET_* environment variables are dumped into the serialized config variables, however they can't be parsed by the cfg loader on load, causing the config loading to be incorrect.  This fixes this issue.

Fix: environment variables starting with XET_* corrupt configs.  

---

rust/cas_client/src/local_client.rs

`std::fs::remove_file` currently corresponds to the `unlink` function on Unix and the `DeleteFile` function on Windows. `unlink` will succeed as long as having write access to the directory. `DeleteFile` fails if the file is read-only.
This PR unsets the read-only attribute for staging files before deletion.
Fix https://github.com/xetdata/xethub/issues/3891

unset readonly flag

---

rust/cas_client/src/caching_client.rs
rust/cas_client/src/interface.rs
rust/cas_client/src/local_client.rs
rust/cas_client/src/passthrough_staging_client.rs
rust/cas_client/src/remote_client.rs
rust/cas_client/src/staging_client.rs
rust/gitxetcore/src/data_processing_v1.rs
rust/gitxetcore/src/data_processing_v2.rs
rust/gitxetcore/src/merkledb_shard_plumb.rs

This PR changes a fundamental interface component of the CAS Client. It allows the put() method to be backgrounded. The background put() capability has been implemented in the PassthroughStagingClient (at the moment that is the most convenient location to enable the xetblob and hence Python API to get parallel uploads).
This means that for corectness, all puts() must be followed by a flush(). I fixed all the locations I can find.

background puts support for CASClient, implemented in PassthroughStagingClient

---

rust/gitxetcore/src/config/log.rs
rust/gitxetcore/src/config/util.rs
rust/gitxetcore/src/data_processing_v1.rs
rust/gitxetcore/src/data_processing_v2.rs
rust/gitxetcore/src/summaries/analysis.rs
rust/gitxetcore/src/summaries/csv.rs
rust/xet_config/src/cfg.rs
rust/xet_config/src/loader.rs

Fix #3921
After 3 warnings, this will be printed:
Warnings now read:
"Summaries for "business.csv" will not be available as parsing errors were detected: [...]"
```
2023-08-25T17:20:45.048120Z  WARN gitxetcore/src/summaries/analysis.rs:67: Too many warnings. No more CSV warnings will be printed.
2023-08-25T17:20:45.048127Z  WARN gitxetcore/src/summaries/analysis.rs:68: You can run 'git xet config --local log.silentsummary true'
2023-08-25T17:20:45.048127Z  WARN gitxetcore/src/summaries/analysis.rs:69: or set the environment variable XET_LOG_SILENTSUMMARY=true to disable all parser warnings
```
Setting the requested config will silence all csv parser warnings

Reduce CSV Parser Warning Aggressiveness

---

rust/gitxetcore/src/xetmnt/mod.rs

Fix #3795
Linux mount not checking exit code correctly

Linux mount not checking exitstatus correctly

---

rust/xetblob/src/bbq_queries.rs
rust/xetblob/src/xet_repo.rs
rust/xetblob/src/xet_repo_manager.rs

Fix https://github.com/xetdata/pyxet/issues/80
1. Invalidates bbq cache on write transaction commit.
2. `xet ls` calls XetRepoManager::listdir, but XetRepoManager uses a different bbq_client from what XetRepo and XetRepoWriteTransaction use. This makes them all use the same bbq_client (and its cache).

invalidate bbq cache on transaction commit

---

rust/gitxetcore/src/command/mount.rs

Remove an unneeded check that will make it easier for sudo-ers to mount.

git user config is not needed on mount

---

rust/gitxetcore/src/data_processing.rs
rust/gitxetcore/src/data_processing_v1.rs
rust/gitxetcore/src/data_processing_v2.rs
rust/xetblob/src/bin/xetcmd.rs
rust/xetblob/src/file_open_flags.rs
rust/xetblob/src/lib.rs
rust/xetblob/src/rfile_object.rs
rust/xetblob/src/xet_repo.rs

Adds a `get` function to download an entire file to disk.
Adds a file open options to disable caching when downloading an entire file.

Faster xetblob download to disk

---

rust/gitxetcore/src/data_processing_v2.rs

There is a bug that if dedupping against a chunk in the local cas aggregator `cas_data`, these chunks in the constructing `file_info` are not tracked and thus not rewritten when the `cas_data` is full and registered.
Test plan:
1. Generate 10 files each of 100K random data: `for i in {0..9}; do dd if=/dev/urandom of=data100K_$i bs=100K count=1; done`.
2. Copy these 10 files 100 times in the round-robin order to a file `data`: `for k in {0..99}; do for i in {0..9}; do cat data100K_$i >> data; done; done`.
3. Under a repo, run `git add data`, `rm data`, `git checkout data`.
Test results:
With `git-xet 0.11.2-e5bdff8`, there were errors that certain cas hash in file info is 0:
```
git-xet 0.11.2 filter started
Xet: Retrieving data blocks: 1.02 MiB | 1.02 MiB/s.
2023-09-08T14:31:13.758698Z …
```

Fix bug in dedup against local cas aggregator

---

rust/gitxetcore/src/xetmnt/watch/metadata/filesystem.rs

Type of root is &mut ...  so mut is redundant

Fixes annoying clippy issue.

---

rust/gitxetcore/src/data_processing_v2.rs
rust/gitxetcore/src/errors.rs
rust/mdb_shard/src/shard_file_manager.rs

Previously, a bad file hash lookup caused an unrecoverable error.  Now, when looking up file reconstruction information fails, an error is printed but the original pointer file is passed through instead.

Smudge now passes bad file reconstruction lookups through as pointers.

---

rust/cas_client/src/staging_client.rs
rust/gitxetcore/src/data_processing.rs
rust/gitxetcore/src/data_processing_v1.rs
rust/gitxetcore/src/data_processing_v2.rs
rust/gitxetcore/src/stream/git_stream.rs
rust/progress_reporting/src/data_progress.rs
rust/progress_reporting/src/main.rs

This PR updates the current progress bar used by the git_stream functions and CAS uploading routines to avoid &mut self, thus allowing it to be easily wrapped by pyxet and passed between python and rust.  This has the additional advantage of avoiding a mutex, as was the case in git_stream.  The base functionality and format has not changed.
To test out the different formats and use cases, run the produced executable test_progress_reporting.   See progress_reporting/src/main.rs for example code.  
```
Testing progress bar (no totals, no bytes): 4 completed, done.
Testing progress bar (total count, no bytes): 100% (5 / 5), done.
Testing progress bar (no totals, only bytes): 14.65 KiB | 9.69 KiB/s, done.
Testing progress bar (only bytes + total): 100% (19.53 KiB / 19.53 KiB) | 9.70 KiB/s, …
```

Update the current progress reporting class for pyxet use.

---

rust/gitxetcore/src/command/repo_size.rs
rust/gitxetcore/src/git_integration/git_repo.rs
rust/gitxetcore/src/merkledb_plumb.rs
rust/gitxetcore/src/merkledb_shard_plumb.rs
rust/gitxetcore/src/summaries_plumb.rs
rust/gitxetcore/src/utils.rs

Currently, the anyhow with_context swallowed all the errors in working with the git notes.  This PR updates all of these so that error reporting is better and informative.

Better error reporting on notes errors.

---

rust/xetblob/src/bbq_queries.rs

This PR adds `User-Agent` header to BBQ clients that detect the different clients from which it was run (xet-cli or pyxet), which provides us a mechanism to detect the client type on server-side. A separate PR for Xetea will be sent out for the server-side change to detect `User-Agent`

Add User-Agent header to BBQ client for xet-cli or pyxet

---

rust/gitxetcore/src/command/smudge.rs
rust/gitxetcore/src/command/summary.rs
rust/gitxetcore/src/data_processing.rs
rust/gitxetcore/src/data_processing_v1.rs
rust/gitxetcore/src/data_processing_v2.rs
rust/gitxetcore/src/diff/fetcher.rs
rust/gitxetcore/src/errors.rs
rust/gitxetcore/src/git_integration/git_repo.rs
rust/gitxetcore/src/merkledb_plumb.rs
rust/gitxetcore/src/smudge_query_interface.rs
rust/gitxetcore/src/xetmnt/xetfs_write.rs
rust/mdb_shard/src/shard_file_manager.rs
rust/pointer_file/Cargo.toml
rust/pointer_file/src/lib.rs
rust/xetblob/src/xet_repo.rs

This PR: 
- Adds checks in data_processing, shard manager, and other places to allow limited operation without a repo present. 
- Added --id/-i flag to git-xet smudge to take a raw hash instead of a pointer file and smudge based on that.  Thus:
```
git xet smudge -i <hash> -o <output_file> 
```
will materialize the file given by the hash ID to the output_file given.

git xet smudge -i <hash> now materializes a file, independent of repo 

---

rust/gitxetcore/src/git_integration/git_repo.rs

In MDBv1 when a mdb diff is big, a xorb is created for this mdb diff, and this happens inside `sync_dbs_to_notes`, after `upload_all_staged`. This calls `upload_all_staged` again after `sync_dbs_to_notes` to push that xorb.

push mdb v1 diff when it is a standalone pointer

---

rust/gitxetcore/src/errors.rs

This PR makes git-xet return different error codes for different error types. This is needed for better error cause parsing in internal projects that use git-xet.

error codes for GitXetRepoError

---

rust/gitxetcore/src/config/axe.rs
rust/xet_config/src/cfg.rs

This flips the default behavior for AXE from enabled-by-default to disabled-by-default. The same env variable XET_AXE_ENABLED is still respected.
Tested locally:
* With no env variable set, no AXE requests are sent
* With env variable XET_AXE_ENABLED=1, AXE requests are sent

Disable AXE by default

---

rust/xet_config/src/console_ser.rs

After merging #136, a unit test now fails in main. This is due to a change in the hardcoded value `axe.enabled`.

Fix unit test failure in main

---

rust/gitxetcore/src/command/mount.rs
rust/gitxetcore/src/config/mod.rs
rust/gitxetcore/src/errors.rs
rust/gitxetcore/src/git_integration/git_repo.rs
rust/gitxetcore/src/git_integration/git_url.rs
rust/gitxetcore/src/git_integration/mod.rs

With this PR git-xet clone and mount work with xet urls in format `xet://[user]/[repo]/[branch]`
1. Path after branch is ignored.
2. If branch is not specified the default branch is used.
3. Branch in the xet url has priority, i.e., `--branch` in git xet clone or `--reference` in git xet mount is ignored if branch exists in the xet url.
The xet url parsing logic is mostly taken from pyxet.
Resolves https://github.com/xetdata/xethub/issues/3859.
Example usage:
`git xet clone xet://[user]/[repo]/[branch]`
`git xet mount xet://[user]/[repo]/[branch]`
Clone Tests:
1. clone with default branch (main) -> main
```
di@di-mbp ~/tt % git xet clone xet://seanses/bsf13 2>/dev/null && cd bsf13 && git branch
* main
```
2. clone with branch p1 in xet url -> p1
```
di@di-mbp ~/tt % git xet clone …
```

git-xet accepts xet url

---

rust/Cargo.toml
rust/gitxet/tests/integration_tests.rs
rust/gitxet/tests/integration_tests/initialize.sh
rust/gitxet/tests/integration_tests/test_xet_version_check.sh
rust/gitxetcore/Cargo.toml
rust/gitxetcore/src/command.rs
rust/gitxetcore/src/config/util.rs
rust/gitxetcore/src/config/xet.rs
rust/gitxetcore/src/errors.rs
rust/gitxetcore/src/git_integration/git_repo.rs
rust/gitxetcore/src/lib.rs
rust/gitxetcore/src/upgrade_checks.rs

This PR adds a version check around many different git xet operations.  
- If the release notes on any version between the latest released version and the current version contain the letters CRITICAL, the user will be asked to upgrade every 2 hours, with a urgent warning:
```
**CRITICAL:**
A new version of the Xet client tools, {version}, is available at https://github.com/xetdata/xet-tools/releases and contains a critical bug fix from your current version.  Upgrading to this release immediately is strongly recommended.
```
- Otherwise every 24 hours the user will see:
```
A new version of the Xet client tools, {version}, is available at https://github.com/xetdata/xet-tools/releases.
```
Checking is done by polling github.com/xetdata/xet-tools/releases.

Perform version check on certain commands

---

rust/gitxetcore/src/config/xet.rs
rust/gitxetcore/src/data_processing.rs
rust/gitxetcore/src/data_processing_v2.rs
rust/xetblob/src/lib.rs
rust/xetblob/src/xet_repo.rs

Drops git dependency for v2 repos. First query xetea for a repo's MDB version and repo salt.
Passed pyxet/tests/cli_cp_test.py against local xetea.
Depends on https://github.com/xetdata/xet-core/pull/139 and https://github.com/xetdata/xethub/pull/4333
Resolves https://github.com/xetdata/xethub/issues/4132, https://github.com/xetdata/xethub/issues/3927

xetblob removes git dependency

---

rust/gitxetcore/src/git_integration/git_repo.rs

The path previously could create a duplicate salt as incoming refs were not properly synced with local notes.  A salt should never be implicitly created in a repo; this eliminates that path and ensures the internal note sync happens properly.

Bugfix: Salt duplication bugfix.

---

rust/gitxetcore/src/git_integration/git_file_tools.rs
rust/gitxetcore/src/git_integration/git_repo.rs
rust/parutils/src/parallel_utils.rs

Likely needed for some pull workflows.

On implicit init, sync merkledb stuff too.

---

rust/gitxet/tests/integration_tests/test_get_xet_init.sh
rust/gitxetcore/src/git_integration/git_repo.rs

There is an error in which the MerkleDB version of a repo created by the new client is improperly detected by an old client.  This fixes that issue.

Fixed for mdb guard note setting logic.

---

rust/gitxet/tests/integration_tests/initialize.sh
rust/gitxetcore/src/config/log.rs

Currently, the log files are written to a fixed path.  However, with this configuration, it means that the operation logs saved in the integration tests overwrite previous operations, making debugging things with multiple invocations of git difficult.   This PR adds "{timestamp}" and "{pid}" fields to the log path, which allows XET_LOG_PATH to be generate unique file paths for each process log. 
For example,
```
export XET_LOG_PATH="$HOME/logs/log_{timestamp}_{pid}.txt"
```
could result in the log file 
```
logs/log_2023-10-19T15-28-14.580960+00-00_71376.txt
```
In addition, logging now ensures that the directory the log would be written to exists, and that relative paths work correctly.

Logging File improvements.

---

rust/gitxetcore/src/command/merkledb.rs

No actual functionality change. Just disable command paths in `git xet merkledb` that are not implemented.

disable command path not implemented

---

rust/gitxetcore/src/git_integration/git_wrap.rs

This PR adds simple utility functions to read and write files directly on a bare git repo.  
In this PR, these functions are not connected, but these are needed to enable some end-to-end tests that cover the different integration scenarios.

Utility function to read and write directly to a bare repo

---

rust/gitxetcore/src/summaries_plumb.rs

After https://github.com/xetdata/xet-core/pull/154, the summary in git notes is no longer compatible with the struct layout for Serde serialization, which is by design (summaries will be regenerated). Since this is by design, this fix downgrades the error to an info message.

Downgrade summary load error to info

---

rust/gitxetcore/src/git_integration/git_integration_plumb.rs
rust/gitxetcore/src/git_integration/git_repo.rs

Updated how we probe github remotes: 
- If the remote URL formed from the .xet/config.toml file is one of the remotes, then just probe the remote, not both. 
- If one version of https or ssh succeeds, then don't probe the other one. 
- If there is an error, don't log an error -- just swallow it.

Updated logic and error message printing in probing github remote.

---

rust/gitxet/tests/integration_tests/initialize.sh
rust/gitxetcore/src/command.rs
rust/gitxetcore/src/config/log.rs
rust/gitxetcore/src/config/mod.rs
rust/gitxetcore/src/config/util.rs

A simple update that: 
- If XET_PRINT_LOG_FILE_PATH, then the log path is dumped to stderr.
- After the log is set up, the invocation command of the program is logged as the first command.

Adding printing path and logging the invocation command.

---

rust/gitxetcore/Cargo.toml
rust/gitxetcore/src/config/mod.rs
rust/gitxetcore/src/config/permission.rs
rust/gitxetcore/src/config/xet.rs
rust/xetblob/src/xet_repo_manager.rs

Warn on creation of xet folders with elevated privileges. Fix https://github.com/xetdata/xethub/issues/4119. Make the permission issue on xet folder more robust in a future PR.
Examples:
`sudo git xet clone`:
`sudo xet cp`:

.xet folder permission

---

rust/gitxetcore/src/git_integration/git_commits.rs
rust/gitxetcore/src/git_integration/git_repo.rs
rust/gitxetcore/src/git_integration/git_wrap.rs
rust/gitxetcore/src/git_integration/mod.rs

The recently added git xet init functionality is actually broken; this PR fixes it.  
The create_commit function actually discards all previous commits.  This is due to creating a blank index instead of a tree as an intermediate step, then writing this as the commit; however, this sets the current state of the repo, not an update. 
The solution is to use a new, more general atomic commit function to make this happen.   A number of tests are added to cover this scenario.

Fix for git xet init issue on bare repos

---

rust/libmagic/src/file_types.rs
rust/libmagic/src/libmagic.rs

The PR #154 broke summary deserialization by removing a field from the LibmagicSummary type. This was intentional for libmagic summaries, but I didn't realize this would also affect deserialization of CSV summaries since we combine them together in a WholeRepoSummary struct that we then try to deserialize. We still want to be able to read CSV summaries through that struct, so we need to keep this field forever for Serde compat.

Fix summary deserialization compat

---

rust/gitxetcore/src/upgrade_checks.rs

Turned warn! to info! in version check. 
Added some informative logging strings.

Fixed version check warning on .xet/ problems

---

rust/gitxetcore/src/git_integration/git_wrap.rs
rust/gitxetcore/src/upgrade_checks.rs

Disables the version check in all calls spawned downstream from another git-xet process.   Addresses https://github.com/xetdata/xethub/issues/4600 and other cases where the version check message may be swallowed silently due to this.

Disable version check in recursive calls.

---

rust/gitxetcore/src/git_integration/git_wrap.rs

This implements a helper function to list files under a path in a repo, needed by git xet materialize and dematerialize features.

List files from git repo

---

rust/gitxetcore/src/git_integration/git_repo.rs

In our tests the remote is not xet-enabled and a local clone set up the salt.

Push repo salt in case the remote is not xet-enabled

---

rust/gitxet/tests/integration_tests/test_github_integration_simple.sh

git commit seems to barf out an exit code 1 sometimes if it thinks that the file hasn't changed from the index based on timestamps.  This can sometimes causes the test_github_integration_simple test to intermittently fail depending on where the boundary of the 1 second tick used for difference checking.   This PR fixes this.

Fix for intermediate test failure.

---

rust/progress_reporting/src/data_progress.rs

Puts a minimum width for the line we print in our progress bar, with the difference made up with spaces.  This is based on git's messages, which can be longer than ours, causing weird interleaving when the user does stuff to the input (hits a new line, etc.)  .

Pad out spaces on progress monitoring. 

---

rust/gitxetcore/Cargo.toml
rust/xetblob/Cargo.toml

Mac Native TLS takes a long time to load.
https://github.com/rustls/rustls-native-certs/issues/30
This is an issue as some git operations spawn (sequentially) a large number of git-xet subprocesses. This switches reqwest to using an embedded Mozilla certificate roots.  (webpki-roots crate). This reduces push time by about 33%.

Swtich to embedded TLS roots instead of Native TLS

---

rust/gitxetcore/src/git_integration/git_process_wrapping.rs
rust/gitxetcore/src/git_integration/git_xet_repo.rs

This PR disables recursive reference transaction hooks in the MerkleDB v2 case.  It is unclear why they are needed in the MDB v1 case; this warrants further investigation.
On the pre-push hook, this seems to save roughly 1.5 - 2 seconds of time depending on the scenario.

Disable recursive reference transaction hooks

---

.circleci/config.yml
rust/gitxetcore/Cargo.toml
rust/gitxetcore/src/git_integration/git_repo_plumbing.rs

Implements two functions: `walk_working_dir` for walking a repo working directory; `filter_files_from_index` for filtering out untracked files. Needed for `materialize` and `dematerialize` commands.

Plumbing functions for walking working directory

---

rust/gitxetcore/src/errors.rs
rust/gitxetcore/src/git_integration/git_process_wrapping.rs
rust/gitxetcore/src/git_integration/git_xet_repo.rs
rust/gitxetcore/src/merkledb_shard_plumb.rs
rust/gitxetcore/src/summaries_plumb.rs
rust/xetblob/src/xet_repo.rs

This PR speeds up the pre-push hook significantly, cutting down the pre-push hook execution time on the Flickr30k dataset, with one change committed, from 9.5 seconds to 5 seconds.   There are two main parts:
1. Initializing the CAS once, and using it for all operations.   The previous version create a CAS staging client three independent times.  Each time takes well over a second due to the time required to scan the cache folder (another issue, the next one to look at).
2. Running the operations in parallel while respecting the dependencies.  The uploading to the CAS is done in the background for all of it.  Uploading the shards is done in the background until the notes are needed.

Speedup of pre-push hook

---

README.md

The `git-xet` link in the README.md sends users to a 404 page. Seems the documentation page was renamed from "installation" to "install" without a doc update.

Fix git-xet link 404

---

rust/gitxet/tests/integration_tests/test_xet_version_check.sh
rust/gitxetcore/src/upgrade_checks.rs

test_xet_version_check pings the github server a lot, resulting in denials due to API rate limits.  This new version uses a local file cache to reduce this query to once ever 24 hours or so, and then passes still if the query hits such API rate limits.

Updated test_xet_version_check.sh to be robust to API rate limits.

---

rust/gitxetcore/Cargo.toml
rust/gitxetcore/src/command.rs
rust/gitxetcore/src/config/errors.rs
rust/gitxetcore/src/config/mod.rs
rust/gitxetcore/src/config/permission.rs
rust/gitxetcore/src/config/xet.rs
rust/gitxetcore/src/upgrade_checks.rs
rust/xet_config/src/cfg.rs
rust/xet_config/src/lib.rs
rust/xetblob/src/xet_repo_manager.rs

Adds a `xet_home` in XetConfig. Each xet metadata folder/file to access (cache, repos, version_check_info), if not explicitly configured to a different path, will be created or read/written under a checked `xet_home`. Such directories and files will also be checked or created for R+W permissions with `Permission::create_dir_all` or `Permission::create_file`. If the running git-xet process lacks such permission, an error message is printed asking the user to reset the permissions.
Fix https://github.com/xetdata/xethub/issues/4592

Robust .xet permission handling

---

rust/gitxetcore/src/command/smudge.rs
rust/gitxetcore/src/config/xet.rs
rust/gitxetcore/src/data_processing_v2.rs
rust/gitxetcore/src/merkledb_shard_plumb.rs
rust/gitxetcore/src/smudge_query_interface.rs
rust/mdb_shard/src/error.rs

1. update smudge query interface to really allow server only query
2. update smudge command to self retry on mdbv1 smudge, this helps to eliminates `merkledb query` and `merkledb extract-git` on V2 repos on xetea. 
Xetea side PR: https://github.com/xetdata/xethub/pull/4770
Fix https://github.com/xetdata/xethub/issues/3838

Allow server only smudge on Xetea

---

rust/libmagic/src/libmagic.rs

The INFO output in dir-summary would include the libmagic summary for each file, which is too many lines of output when the repo has many files. We don't really need this info, so this commit removes it.

Reduce info output on dir-summary

---

rust/gitxetcore/src/git_integration/git_xet_repo.rs

This can happen if GIT_WORK_TREE is set (e.g.)

Don't try to write the .gitattributes in a bare repo

---

rust/gitxetcore/src/config/git_path.rs
rust/gitxetcore/src/config/user.rs
rust/gitxetcore/src/config/util.rs
rust/gitxetcore/src/config/xet.rs
rust/gitxetcore/src/config_cmd.rs

So running pyxet on a machine without git will not fail. Fix https://github.com/xetdata/xethub/issues/4816

ConfigGitPathOption::NoPath doesn't invoke git

---

rust/mdb_shard/src/intershard_reference_structs.rs

The issue was that the IntershardReference class used the entries vector to track everything, but the num_entries field of the header was not caught up to date.  In most cases this results in entries being ignored, but in the case of the corruption I witnessed, the value in the num_entries field was much larger than the number of entries.

Possible fix for shard corruption issue.

---

rust/mdb_shard/src/intershard_reference_structs.rs
rust/mdb_shard/src/session_directory.rs
rust/mdb_shard/src/shard_format.rs

The previous fix for the shard issue didn't fully fix the problem; this addresses another (and hopefully final) issue.

Fix #2 for shard corruption issue.

---

rust/Cargo.toml
rust/cas_client/Cargo.toml
rust/cas_client/src/staging_client.rs
rust/common_constants/Cargo.toml
rust/common_constants/src/lib.rs
rust/gitxetcore/Cargo.toml
rust/gitxetcore/src/command/filter.rs
rust/gitxetcore/src/config/log.rs
rust/gitxetcore/src/constants.rs
rust/gitxetcore/src/stream/git_stream.rs

Updated what gets printed on filter and pre-push hooks.  
- Eliminated the git-xet filter started message. 
- Moved version info to the progress printing.
- Moved constants to a common spot so places outside of gitxetcore can access constants not needed for git integration.
Now, instead of the filter printing on dedup:
```
git-xet 0.12.8 filter started
Xet: Deduplicating data blocks: 54.15 MiB | 54.15 MiB/s, done.
```
It now prints just:
```
Git-Xet 0.12.8: Processing data: 54.15 MiB | 54.15 MiB/s, done.
```
Instead of printing on download:
```
git-xet 0.12.8 filter started
Xet: Downloading data blocks: 54.15 MiB | 54.15 MiB/s, done.
```
It now prints just:
```
Git-Xet 0.12.8: Downloading data: 54.15 MiB | 54.15 MiB/s, done.
```
And on push upload, instead of:
```
"Xet: Uploading data …
```

Updated printing around the filter and pre-push process. 

---

rust/gitxetcore/src/config/cas.rs
rust/gitxetcore/src/config/errors.rs
rust/gitxetcore/src/config/util.rs
rust/gitxetcore/src/data_processing_v1.rs
rust/gitxetcore/src/data_processing_v2.rs
rust/xet_config/src/cfg.rs
rust/xet_config/src/loader.rs

Changes the small file threshold used in the pointer file translators from a constant to a config (e.g. `XET_CAS_SIZETHRESHOLD`). This allows applications like xet sync to treat all uploaded files as pointer files (by setting the threshold to 0) so that the sync doesn't overwhelm XetHub when uploading a dataset of thousands of moderately sized (~100KB) text files. 
We limit this config to be in the range: `[0, SMALL_FILE_THRESHOLD]` so that users don't try to upload files larger than our current pointer-file threshold.

Adding size threshold as a config

---

rust/cas_client/src/grpc.rs
rust/utils/Cargo.toml
rust/utils/proto/common.proto
rust/utils/src/lib.rs

Adds root ca certificate field to CAS Initiate Response needed for upcoming Encryption in Transit work.

cas protocol initiate root ca field

---

rust/gitxetcore/src/data_processing_v2.rs
rust/gitxetcore/src/merkledb_shard_plumb.rs

Reports progress when downloading MerkleDB on repo cloning. This can take a while on large repos.
Fix https://github.com/xetdata/xethub/issues/4939

Progress reporting for downloading mdb

---

.github/workflows/commit.yml

Partly resolves https://github.com/xetdata/xethub/issues/4915
Unfortunately, removing #[async_trait] from xet-core makes it unable to compile. So let's not convert at the moment.

use rust 1.75.0

---

rust/Cargo.toml
rust/cas_client/Cargo.toml
rust/cas_client/src/caching_client.rs
rust/error_printer/Cargo.toml
rust/error_printer/src/lib.rs
rust/gitxetcore/Cargo.toml
rust/gitxetcore/src/command/repo_size.rs
rust/gitxetcore/src/diff/fetcher.rs
rust/gitxetcore/src/git_integration/git_repo_salt.rs
rust/gitxetcore/src/log.rs
rust/gitxetcore/src/upgrade_checks.rs
rust/gitxetcore/src/xetmnt/watch/metadata.rs
rust/gitxetcore/src/xetmnt/watch/metadata/cache.rs
rust/gitxetcore/src/xetmnt/watch/metadata/filesystem.rs
rust/gitxetcore/src/xetmnt/watch/metadata/symbol.rs
rust/gitxetcore/src/xetmnt/watch/watcher.rs
rust/gitxetcore/src/xetmnt/watch/xetfs_watch.rs

Make ErrorPrinter trait be exported out of it's own error_printer crate so that it can be imported from non-gitxetcore crates as well as projects outside of this repository.
Expand the ErrorPrinter trait to give info_error and debug_error functions so that we can log with different tracing levels.

pull out error printer and some usages

---

rust/cas_client/Cargo.toml
rust/cas_client/src/cas_connection_pool.rs
rust/cas_client/src/data_transport.rs
rust/cas_client/src/grpc.rs
rust/cas_client/src/remote_client.rs
rust/shard_client/Cargo.toml
rust/shard_client/src/shard_client.rs

This PR should not merge before EOD PST of Tuesday 1/23/2024.
- Bump CAS Protocol version.
- Makes git-xet client's cas_client use the HTTPS data plane CAS protocol.
- processes certificate from initiate requests.

git-xet client uses HTTPS endpoint

---

rust/gitxet/tests/integration_tests/initialize.sh
rust/gitxetcore/src/command/clone.rs
rust/gitxetcore/src/command/dir_summary.rs
rust/gitxetcore/src/command/merkledb.rs
rust/gitxetcore/src/command/repo_size.rs
rust/gitxetcore/src/command/summary.rs
rust/gitxetcore/src/constants.rs
rust/gitxetcore/src/data_processing.rs
rust/gitxetcore/src/data_processing_v2.rs
rust/gitxetcore/src/git_integration/git_notes_wrapper.rs
rust/gitxetcore/src/git_integration/git_repo_plumbing.rs
rust/gitxetcore/src/git_integration/git_repo_salt.rs
rust/gitxetcore/src/git_integration/git_user_config.rs
rust/gitxetcore/src/git_integration/git_xet_repo.rs
rust/gitxetcore/src/merkledb_plumb.rs
rust/gitxetcore/src/merkledb_shard_plumb.rs
rust/gitxetcore/src/summaries_plumb.rs
rust/gitxetcore/src/utils.rs

This PR updates the logic around handling the user.name and user.email fields in the config.  These were needed for adding notes, as the notes needed a signature field to be filled out.  However, as these fields are rarely visible, we now use the following logic: 
- If user.name and user.email are available from git, use those.   
- Otherwise, if the user name and email are available from the xet config, use those. 
- Finally, if none of these are available, use "Xet System" for the name and "system@xethub.com" for the backup values. 
Now, with this change, there are no longer any checks for these fields.   Tests are updated to ensure they work in this environment.  
Resolves https://github.com/xetdata/xethub/issues/5021, https://github.com/xetdata/xethub/issues/4718, …

Updated logic around user name and user email

---

rust/gitxet/tests/integration_tests/test_stored_notes.sh

test_stored_notes was really slow using loops to create a large CSV file.  Using a different bash construct and turning off the set -x call for these parts vastly speeds up this test.

Cut running time of test_stored_notes to < 5s.

---

rust/gitxetcore/src/command/summary.rs
rust/gitxetcore/src/data/data_processing_v1.rs
rust/gitxetcore/src/data/data_processing_v2.rs
rust/gitxetcore/src/diff/fetcher.rs
rust/gitxetcore/src/summaries/csv.rs

Pass the `\t` delimiter through wherever we can detect that the file is a TSV rather than CSV. Previously, the csv_core module assumed a `,` delimiter wherever it was used.

Add proper support for summarizing TSV

---

rust/cas_client/src/local_client.rs
rust/cas_client/src/remote_client.rs
rust/gitxetcore/src/stream/git_stream_frame.rs
rust/lazy/src/lazy_pathlist_config.rs
rust/merkledb/src/internal_methods.rs
rust/shard_client/src/lib.rs
rust/xet_error/impl/src/lib.rs

Locally upgraded rust to v. 1.76.0; this PR fixes new clippy errors.

Fixed new clippy errors from upgraded rust version.

---

rust/gitxetcore/Cargo.toml
rust/mdb_shard/src/constants.rs
rust/mdb_shard/src/lib.rs
rust/mdb_shard/src/shard_format.rs
rust/shard_client/src/local_shard_client.rs
rust/xetblob/Cargo.toml

Since the sampling proportion is a value shared by all clients and the server, and it's used as a constant anyway, it makes sense to just fold it into the code.
This will require a slight update on the xethub side once this PR is merged in.

Rename constant for global dedup queries; redo API to use constant internally.

---

rust/gitxet/tests/integration_tests.rs
rust/gitxet/tests/integration_tests/initialize.sh

Speeds up the integration tests by not making them run at debug level by default.  They will now respect local environment variables when run locally.

Make integration tests run faster

---

rust/gitxetcore/src/data/data_processing_v2.rs

When new shards are discovered for global dedup, log them to info (instead of just debug).

Better logging for global dedup

---

rust/progress_reporting/src/data_progress.rs

Feedback was that the percentage indicator can be confusing especially for settings where the denominator is dynamic (ex: being filled by a directory enumeration running in the background)

Remove Percentage indicator

---

rust/gitxetcore/Cargo.toml

This avoids openssl compilation issues in pyxet, and avoids having multiple openssl versions packed in our executable.

Turn off remote capabilities in git2

---

rust/gitxetcore/src/environment/log.rs

This PR:
- lowers the exception backtrace logging level to info in most situations so that it never shows up to users, but does keep the information there. 
- Logged at error level in telemetry situations.

Lower exception backtrace from error to info so it won't accidentally show up. 

---

rust/gitxetcore/src/git_integration/git_url.rs

In order to use `git xet cp` for our upload function, it needs to be able to target our service running on localhost. This requires that we are able to specify the domain as well as the port in our endpoint override.

Adding port to the endpoint override

---

rust/gitxetcore/src/data/mdb.rs
rust/gitxetcore/src/xetblob/bbq_queries.rs
rust/gitxetcore/src/xetblob/mod.rs
rust/gitxetcore/src/xetblob/xet_repo.rs
rust/gitxetcore/src/xetblob/xet_repo_manager.rs

Related issue: https://github.com/xetdata/xethub/issues/5518
With global dedup the repo salt is used to query dedup shards. Right now repo salt is downloaded once and stored into a local folder with name computed from the tuple `(remote, username, token)`. If a user deletes a repo and creates one with the same name pyxet and git-xet cp don't detect this change will use the invalid repo salt on disk. 
In this PR:
- xetblob verifies the repo salt on every repo open: if the salt doesn't match delete all files under the directory.
- removes message "Initializing repository on first access\nInitialization complete" for first accessing a v2 repo.
Tests:
pytest tests:
```
(.env) di@di-mbp ~/xetdata/pyxet/python/pyxet % pytest tests …
```

Refresh repo salt on every repo open

---

rust/cas_client/src/data_transport.rs
rust/utils/src/compression.rs
rust/utils/src/lib.rs

Adds header on client to accept encoding, though set to none at the moment until server side implementation can support and respect this header.
This PR is needed so that the CAS server can use utils::CompressionScheme and share the header values.

prelude to compression on the wire for dataplane

---

rust/gitxetcore/src/command/login.rs
rust/gitxetcore/src/config/authentication.rs
rust/xet_config/src/cfg.rs
rust/xet_config/src/loader.rs

This PR enables the reading and writing of xethub S3 credentials to xet config.
Running "git-xet login" without the s3 option will print the following
```
Set the following environment variables to use AWS cli
Re-run `git-xet login` with the --s3 option to write these keys to an AWS cli configuration profile
AWS_ACCESS_KEY_ID = blah
AWS_SECRET_ACCESS_KEY = blah
To see the repos you have access to via S3,
set the environment variables above and run:
aws --endpoint-url=s3.xethub.com s3 ls
```
Also, adds the --s3 option will try to write the config and will print the following message:
```
The following was config written successfully to AWS cli configuration.
AWS_ACCESS_KEY_ID = blah
AWS_SECRET_ACCESS_KEY = blah
To see the repos you have access to via S3, run:
aws …
```

Enable git-xet login with s3 credentials

---

rust/cas_client/src/data_transport.rs
rust/cas_client/src/grpc.rs
rust/utils/proto/common.proto
rust/utils/src/compression.rs
rust/utils/src/lib.rs

Refactor CompressionScheme type to be defined in protobuf so the CAS server will report accepted encodings for put operation.

compression refactor to protobuf type

---

rust/gitxetcore/src/summaries/constants.rs
rust/gitxetcore/src/summaries/csv.rs
rust/gitxetcore/src/summaries/mod.rs

Fix https://github.com/xetdata/xethub/issues/5559
With this PR by default a CSV summary will not be created for files under 256 KiB. This can be tuned by `export XET_CSV_MIN_SIZE = [file size in bytes]`

Add threshold to csv summary

---

rust/cas_client/Cargo.toml
rust/cas_client/src/data_transport.rs
rust/cas_client/src/grpc.rs
rust/cas_client/src/remote_client.rs

client side work adding LZ4 compression in transit on the CAS H2 dataplane.
- on the download path, client advertises acceptable formats via an H2 request header
- on upload path, CAS server will reply with acceptable formats in gRPC InitiateResponse

client work cas compression in transit

---

rust/gitxetcore/src/command/dir_summary.rs
rust/gitxetcore/src/command/summary.rs
rust/gitxetcore/src/diff/fetcher.rs
rust/gitxetcore/src/summaries/analysis.rs
rust/gitxetcore/src/summaries/summaries_plumb.rs

Moves the Tableau summaries to a versioned `SummaryExt` struct that will hold additional summaries. This seems to be working locally for csv files summarized earlier and seems to work for tableau files too.

Fix Summary Schema

---

rust/error_printer/src/lib.rs

The current error_printer implementation makes it difficult to track where the errors come from, because `error!()`, `warn!()`, `info!()`, `debug!()` all log calling location with `file!()` and `line!()`, which is inside `error_printer/src/lib.rs`. For example, using error_printer inside `gitxetcore/src/command/merkledb.rs` like below
```
use error_printer::ErrorPrinter;
let err = GitXetRepoError::CasClientError("hello".to_owned());
let eerr = Err::<(), GitXetRepoError>(err);
eerr.log_error("log error")
.warn_error("warn error")
.debug_error("debug error")
.info_error("info error");
```
will print
```
2024-03-22T23:10:14.190210Z ERROR gitxet: error_printer/src/lib.rs:20: log error, error: CasClientError("hello") 
2024-03-22T23:10:14.190316Z  WARN gitxet: error_printer/src/lib.rs:30: warn …
```

Error Printer track caller

---

rust/error_printer/src/lib.rs

This makes the logging functions in ErrorPrinter to also include a backtrace.

Add backtrace to ErrorPrinter

---

rust/error_printer/src/lib.rs
rust/gitxetcore/src/environment/log.rs

Reverts xetdata/xet-core#310. It adds too much backtrace and it's not helpful because at the time of calling the logging functions `log_error` etc. the backtrace for where the error was first generated is already gone.

Revert "Add backtrace to ErrorPrinter"

---

rust/tableau_summary/src/twb/mod.rs
rust/tableau_summary/tests/twb_test.rs

Fixes: TAB-50
* Allows the TWB summary to summarize files without dashboards.

Allow empty dashboards in TWB summary

---

rust/gitxetcore/Cargo.toml
rust/gitxetcore/src/command/summary.rs
rust/gitxetcore/src/summaries/csv.rs

Adds functionality to smudge from CAS hash then pass through to CSV/TWB/TDS file summarizers. With custom arg to specify delimiter since we don't have the file extension.

smudge and summarize

---

rust/gitxetcore/src/command/summary.rs
rust/gitxetcore/src/errors.rs

- Adds a git-xet summary subcommand to summarize file contents from stdin
- minor refactors of summary.rs functions, shared code between different compute command impls
- adds a `-f/--force` on `git-xet summary compute-from-blob-id` that skips attempting to look in summary DB in git notes
- for blob that holds a pointer file, this will attempt to compute the hash by smudging the hash.

summarize compute from stdin and add force option for from-blob-id

---

rust/tableau_summary/Cargo.toml
rust/tableau_summary/src/twb/raw/dashboard.rs
rust/tableau_summary/src/twb/raw/datasource/connection.rs
rust/tableau_summary/src/twb/raw/util.rs
rust/tableau_summary/src/twb/raw/worksheet.rs

Fixes: TAB-52
* Thumbnails are extracted using the last path element of the `derived-from` field of the `repository-location` node if that is different from the `id` column.
* Fixes an issue where `measure` classes in `metadata-records` were being ignored during parsing.

Fixing Thumbnail extraction name from twb files

---

rust/gitxetcore/src/command/clone.rs
rust/gitxetcore/src/config/xet.rs

Fixes CLI-144 [->](https://linear.app/xethub/issue/CLI-144/xet-no-smudge-doesnt-work-with-git-xet-clone). 
Context:
When cloning a repo "no smudge" can be configured from three places in order of descending priority:
1. command line args: `git xet clone --lazy/--no-smudge`
2. env var `XET_NO_SMUDGE=1`
3. git-xet global config, e.g. `git xet config --global smudge false`.
The bug was that `XET_NO_SMUDGE` was dropped from the env var but the config not used by `git xet clone`. It was dropped in https://github.com/xetdata/xet-core/pull/87 to avoid a config parsing issue which was later fixed by https://github.com/xetdata/xet-core/pull/95, making it unnecessary to drop `XET_NO_SMUDGE`.
This PR fixes the XetConfig to make sure it picks up the corresponding global config and env var config, and …

Handles no smudge config correctly

---

rust/gitxetcore/src/command/diff.rs
rust/gitxetcore/src/diff/mod.rs
rust/gitxetcore/src/diff/output.rs
rust/gitxetcore/src/diff/tds.rs
rust/gitxetcore/src/diff/twb.rs

Fixes: TAB-47
* Adds a summary diff processor for twb files that just provides the before/after summaries
* Adds a summary diff processor for tds files that just provides the before/after summaries

Adding simple summary diffs for twb and tds files

---

rust/merklehash/Cargo.toml
rust/merklehash/src/data_hash.rs

Uses operations that will be correct universally. 
Fixes @CLI-166.

Fixing possible unaligned exception on client.

---

rust/tableau_summary/src/twb/mod.rs
rust/tableau_summary/src/twb/raw/datasource.rs
rust/tableau_summary/src/twb/raw/worksheet/table.rs

Fixes: TAB-65
Sometimes, column resolution for Dashboards and Worksheets needs to use the Datasource's column listing. This change adds the dependency so that we can properly resolve columns.

Add RawDatasource dependency to View struct

---

rust/gitxetcore/src/config/git_path.rs
rust/gitxetcore/src/config/xet.rs
rust/gitxetcore/src/data/cas_interface.rs
rust/gitxetcore/src/data/mdb.rs
rust/gitxetcore/src/environment/axe.rs
rust/gitxetcore/src/git_integration/git_notes_wrapper.rs
rust/gitxetcore/src/git_integration/git_repo_paths.rs
rust/gitxetcore/src/git_integration/git_repo_plumbing.rs
rust/gitxetcore/src/git_integration/git_repo_salt.rs
rust/gitxetcore/src/git_integration/git_user_config.rs
rust/gitxetcore/src/git_integration/git_xet_repo.rs
rust/gitxetcore/src/utils.rs
rust/gitxetcore/src/xetblob/xet_repo.rs

Removes paths that automatically discover git remotes and config information from the current directory when config is not provided.  
Now, the repo path is set in XetConfig at the start, possibly from the current directory, but parts of the code that previously just defaulted to automatic discovery have been reworked.

Remove automatic git path discovery when not in git repository.

---

rust/gitxetcore/src/command/login.rs
rust/gitxetcore/src/command/mod.rs
rust/gitxetcore/src/command/s3config.rs
rust/gitxetcore/src/config/authentication.rs
rust/xet_config/src/cfg.rs
rust/xet_config/src/lib.rs
rust/xet_config/src/loader.rs

Fix CLI-164.
Run `git xet s3config [--host ..]` to pick up login information from ~/.xetconfig to create a env file for AWS CLI. Users will source this env file to pick up `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` and `AWS_ENDPOINT_URL`. After that users can directly run `aws s3 ...` to operate with XS3.
- **If no access_key or secret_key found in the .xetconfig corresponding profile, print**
```
No XetHub authentication found.
Create a new personal access token at https://xethub.com/user/settings/pat
and run the displayed `git xet login` command to authenticate.
Re-try your s3config command after logging in.
```
- **If no xs3 server address found in the .xetconfig corresponding profile ( this can happen if either**
**1. XS3 service is not available for this XetHub deployment;**
**2. …

s3config replace login for xs3 auth UX flow

---

rust/tableau_summary/src/twb/summary/dashboard.rs
rust/tableau_summary/src/twb/summary/worksheet.rs

Fixes: TAB-77
* Titles in Twb worksheets and dashboards that reference a Column/ColumnInstance will be properly templated to their correct column name:

Resolve column names in titles

---

rust/tableau_summary/src/twb/raw/datasource/columns.rs
rust/tableau_summary/src/twb/raw/worksheet/table.rs

Fixes: TAB-78
* Allows table aggregations to be correctly resolved in template strings by using the correct key name in the column map and using the caption when summarizing.
For example:
```
COUNT([pcto:cnt:Orders_6D2EF74F348B46BDA976A7AEEA6FB5C9:qk:1])
```
becomes:
```
COUNT(Orders)
```

Allow templates to use table aggregation column

---

gitxet/Cargo.lock
gitxet/Cargo.toml
libxet/Cargo.toml

The executable in gitxet/ did not get the version string properly updated.  This PR fixes this.

Update gitxet/Cargo.toml version string

---

rust/chunkpipe/src/lib.rs
rust/gitxetcore/src/command/diff.rs
rust/gitxetcore/src/command/summary.rs
rust/gitxetcore/src/data/data_processing_v1.rs
rust/gitxetcore/src/data/data_processing_v2.rs
rust/gitxetcore/src/diff/fetcher.rs
rust/gitxetcore/src/diff/mod.rs
rust/gitxetcore/src/diff/output.rs
rust/gitxetcore/src/diff/tds.rs
rust/gitxetcore/src/diff/twb.rs
rust/gitxetcore/src/git_integration/git_url.rs
rust/gitxetcore/src/summaries/analysis.rs
rust/gitxetcore/src/summaries/csv.rs
rust/gitxetcore/src/summaries/summaries_plumb.rs
rust/gitxetcore/src/xetblob/file_operations/cp_operations.rs
rust/utils/src/compression.rs
rust/utils/src/lib.rs

A bunch of code has crept in that has not had cargo format properly run on it, which results in PRs with a lot of formatting changes when editors that automatically do run cargo fmt touch a file.  
This PR updates a big chunk of these format changes (the rest are in active development, so will hold off on those).

Run cargo fmt

---

rust/gitxetcore/src/command/clone.rs
rust/gitxetcore/src/command/lazy.rs
rust/gitxetcore/src/command/mod.rs

Fix a couple of issues regarding git-xet help messages, hides a couple of git xet commands that are only meant for internal usage and never exposed in public docs. Fix CLI-24, CLI-56, CLI-148
**Recommend to review with whitespaces hidden.**

help message fixes

---

gitxet/Cargo.toml

Compiling git-xet with lto, which is default in release mode, takes around 3 minutes to link.  This adds a local release dev profile invoked by 
`cargo build --profile=rdev` 
that builds the client in release mode but without lto.   This is substantially faster.

Added additional rdev that creates a release binary but without lto

---

rust/tableau_summary/src/twb/diff/dashboard.rs
rust/tableau_summary/src/twb/diff/util.rs

Fixes: TAB-86
Changes the count of zone changes to only be 1 if any of the fields changes.

Fix Zone change count 

---

rust/gitxetcore/Cargo.toml
rust/merkledb/Cargo.toml
rust/merklehash/Cargo.toml

As of version 1.4, blake3 now has optimized M1 / Neon support.  This PR upgrades our version to take advantage of those speedups.

Upgrade blake3 for optimized Arm64 / M1 support.

---

gitxet/Cargo.lock
rust/gitxetcore/Cargo.toml
rust/gitxetcore/src/data/data_processing_v2.rs
rust/gitxetcore/src/data/mdb.rs
rust/mdb_shard/src/cas_structs.rs
rust/mdb_shard/src/set_operations.rs
rust/mdb_shard/src/shard_format.rs
rust/mdb_shard/src/shard_in_memory.rs

Fix BAC-162
Tests:
1. Under a repo with history before this, add a csv file of 373909 bytes
```
di@di-mbp ~/tt/pyxet-build % git xet merkledb cas-stat
{
"total_cas_bytes" : 559694603,
"total_file_bytes" : 559917404
}
di@di-mbp ~/tt/pyxet-build % ls -l
total 1062232
-rw-r--r--@ 1 di  staff     373909 May  6 14:22 Stocks_data (1).csv
-rw-r--r--  1 di  staff  527042656 May  6 14:22 rpyxet.abi3.so
-rw-r--r--  1 di  staff   16437430 May  6 14:22 xet-linux-arm64.tar.gz
di@di-mbp ~/tt/pyxet-build % git add .
Git-Xet 0.13.4: Processing data: 16.03 MiB | 16.03 MiB/s, done.
16.03 MiB added, stored 110.65 KiB (99.3% reduction)
di@di-mbp ~/tt/pyxet-build % git commit -m "add stock data"
[main e73a7fc] add stock data
1 file changed, 3 insertions(+)
create mode 100644 Stocks_data (1).csv
di@di-mbp …
```

Report xorb compression size

---

rust/gitxetcore/src/diff/output.rs
rust/gitxetcore/src/diff/tds.rs
rust/tableau_summary/src/tds/diff/mod.rs
rust/tableau_summary/src/tds/diff/schema.rs
rust/tableau_summary/src/tds/mod.rs

Fixes: TAB-74
Changes the diffs for Tds files to provide more detailed information (i.e. the same as twb datasource diffs).
(Note: will need to apply changes to xdiff once merged).

Adding tds diff v1

---

rust/gitxetcore/src/command/mod.rs
rust/gitxetcore/src/command/repo.rs

In discussion with @erinys, change API of `git xet migrate` to `git xet repo migrate` in order to allow for more repo level commands in the future.  API is the same for the command itself.

Moved `git-xet migrate` to `git xet repo migrate`

---

rust/gitxetcore/src/data/data_processing_v2.rs

lz4 compressed size can be larger than the original size. For example, I added `10/` and `11/` under https://xethub.com/XetHub/Flickr30k/src/branch/main/flickr30k_images and got:
```
di@di-mbp ~/tt/int64 % git add .
Git-Xet 0.13.4: Processing data: 76.37 MiB | 23.10 MiB/s, done.
76.37 MiB added, stored 76.63 MiB (-0.3% reduction)
```

Fix compression reporting bug

---

rust/tableau_summary/src/twb/raw/worksheet/table.rs

Fixes: TAB-104
Adds the special columns: `[Latitude (generated)]` and `[Longitude (generated)]` to column resolution as they're not specified in the datasources and are autogenerated by Tableau whenever a geo field is present.

Adding Lat/Lon as special columns in worksheet/dashboard View

---

rust/gitxetcore/src/xetblob/xet_repo.rs

We added an extra field `cas` to the RepoInfo struct. `serde` parsing old saved info will fail. Tested locally that this will overwrite the repo metadata file on parse failure and then carry on operations correctly.

Overwrite xetblob file on parse failure

---

rust/tableau_summary/src/twb/summary/dashboard.rs

Fixes: TAB-114
Now when a user puts an image in their dashboard (type: `bitmap`), we extract the name of the image properly.

Allow bitmap zones

---

rust/tableau_summary/Cargo.toml
rust/tableau_summary/src/tds/mod.rs
rust/tableau_summary/src/twb/diff/dashboard.rs
rust/tableau_summary/src/twb/diff/datasource.rs
rust/tableau_summary/src/twb/diff/schema.rs
rust/tableau_summary/src/twb/diff/util.rs
rust/tableau_summary/src/twb/diff/worksheet.rs
rust/tableau_summary/src/twb/mod.rs
rust/tableau_summary/src/twb/summary/dashboard.rs
rust/tableau_summary/src/twb/summary/datasource.rs
rust/tableau_summary/src/twb/summary/worksheet.rs

Fixes: TAB-87
Switches diffs to use the Myers diff algorithm implemented using the [imara-diff](https://github.com/pascalkuthe/imara-diff) crate, allowing for minimal diffs between two lists of items.
* Summary/Diff structs  need to have `Eq + Hash` traits defined.
* Adds a `DiffTokenSource` to provide tokens from a list of some T to the diff algorithm.
* Adds a `DiffSync` to process "hunks" of changes that the diff algorithm produces (e.g. `before[1..3]` and `after[2..4]` differ).

Better list diffs for Twb/Tds summaries

---

rust/tableau_summary/src/twb/diff/dashboard.rs
rust/tableau_summary/src/twb/mod.rs
rust/tableau_summary/src/twb/raw/dashboard.rs
rust/tableau_summary/src/twb/summary/dashboard.rs

Fixes: TAB-115
Since the `<zones>` tag might have multiple `<zone>` tags within, we need to change the Raw and Summary Dashboards to support this.
Note: this bumps up the schema version of the TwbSummary to 3 since this is a type change. We should make sure that the UI is able to accept these V3 schemas before merging.

Change zones to be allow multiple top-level Zone objects

---

rust/tableau_summary/src/twb/raw/util.rs

Fixes: TAB-116
Updates thumbnail-name to special-case public.tableau.com since the format of the `repository_location` tag uses the `id` column for the name instead of the last path element of the url.

Special case public workbooks

---

rust/cache/src/disk/cache.rs
rust/cas_client/src/caching_client.rs
rust/cas_client/src/data_transport.rs
rust/cas_client/src/grpc.rs
rust/gitxetcore/src/config/xet.rs
rust/gitxetcore/src/data/data_processing_v2.rs
rust/gitxetcore/src/data/mdb.rs
rust/gitxetcore/src/data/remote_shard_interface.rs
rust/gitxetcore/src/xetblob/bbq_queries.rs
rust/gitxetcore/src/xetblob/xet_repo.rs
rust/mdb_shard/src/shard_file_handle.rs
rust/mdb_shard/src/shard_file_manager.rs
rust/mdb_shard/src/shard_format.rs
rust/mdb_shard/src/shard_in_memory.rs
rust/shard_client/src/shard_client.rs

info! is too verbose for a lot of things that have been stable for a while, so this drops many of these to debug to make info! more informative.  This also adds some summary info! commands that pull together larger blocks of statements with more aggregation. 
Also, for tracking transactions, this PR adds a tag field so that reporting on transactions can be traced.

Drop some info statements to debug.

---

rust/shard_client/src/shard_client.rs

From 4MB to 256MB to allow reconstruction metadata for really large files

Upping grpc message size

---

gitxet/Cargo.lock
rust/merkledb/src/async_chunk_iterator.rs

When using large buffers in the low variance chunking algorithm, the chunker will scan all the way to the end of the buffers even when it's way past the max_chunk_size.  This can cause near-quadratic behavior.  This PR limits the read to the max that can be part of the next chunk.

Fixes significant slowdown when chunking huge buffers of constant data.

---

gitxet/Cargo.lock
libxet/Cargo.lock
rust/gitxetcore/Cargo.toml
rust/gitxetcore/src/config/xet.rs
rust/gitxetcore/src/git_integration/git_url.rs

Fix CLI-199. On cas endpoint probing, if a repo is using an SSH remote url, we translate it to an HTTPS url.
Test:
```
di@di-mbp ~/tt/flyte-data % git remote -v
origin	xet@xethub.com:seanses/flyte-data.git (fetch)
origin	xet@xethub.com:seanses/flyte-data.git (push)
di@di-mbp ~/tt/flyte-data % git show HEAD:owid-covid-data.csv
filesize = 93509074
hash = '0aa378d80cc13e4dce00dc1150aae14c25af2c273c63df789117c6cdcae5b86b'
di@di-mbp ~/tt/flyte-data % git xet merkledb query . 0aa378d80cc13e4dce00dc1150aae14c25af2c273c63df789117c6cdcae5b86b
MDBFileInfo { metadata: FileDataSequenceHeader { file_hash: 0aa378d80cc13e4dce00dc1150aae14c25af2c273c63df789117c6cdcae5b86b, file_flags: 0, num_entries: 6, _unused: 0 }, segments: [FileDataSequenceEntry { cas_hash: …
```

ssh to https url

---

scripts/update_version.sh

There have been several issues with the version changing code currently in use: 
- version of a dependency gets updated if specified using some forms of Cargo.toml syntax.
- libxet/Cargo.lock keeps not getting updated. 
In addition, convenience scripts are convenient. 
This PR introduces a script, run as ./scripts/update_version.sh, that does all the version updating correctly.

Convenience script for updating the version

---

rust/gitxetcore/src/command/dir_summary.rs

Now that dir summaries are cached server side, caching in git notes is redundant. Removing it should also help mitigate some random lockfile related bugs we've seen related to the dir-summary notes lockfiles.

Remove git notes caching for dir summaries

---

rust/gitxetcore/src/command/mount.rs
rust/gitxetcore/src/git_integration/git_process_wrapping.rs
rust/gitxetcore/src/git_integration/git_repo_plumbing.rs

Fix Fun-89.
Test locally, note that only the server reply "repo.access_denied_free_trial%!(EXTRA string=http://localhost:3000///subscription/upgrade)" is printed.
- Mount
```
di@di-mbp ~/tt % git xet mount http://localhost:3000/seanses-local/pyxet.git
Mounting to "/Users/di/tt/pyxet"
repo.access_denied_free_trial%!(EXTRA string=http://localhost:3000///subscription/upgrade)
Error : failed to mount
```
- Writable Mount
```
di@di-mbp ~/tt % git xet mount http://localhost:3000/seanses-local/pyxet.git --writable
Writable mounts are currently an EXPERIMENTAL feature. Be warned. You might lose data!!
Known issues: Performance is poor.
Raw clone at "/Users/di/tt/pyxet_raw".
Mounting at "/Users/di/tt/pyxet".
You can access and make arbitrary modification in the mounted path and changes
will …
```

Show server message nicely on mount

---

rust/gitxetcore/src/command/merkledb.rs

Xetea [GetXetDirSummary](https://github.com/xetdata/xethub/blob/13542f1cdb7a7d6c4de38e1b1b0827c51dc70194/golang/xetea/modules/context/xet.go#L83) and [GetDiff](https://github.com/xetdata/xethub/blob/13542f1cdb7a7d6c4de38e1b1b0827c51dc70194/golang/xetea/services/gitdiff/gitdiff.go#L1274) call `merkledb extract-git` for MDBV1 compatibility. This PR disables fetching all shards by default for V2 repos so there's less burden on Xetea. Fix [CLI-224](https://linear.app/xethub/issue/CLI-224/merkledb-extract-git-takes-long-time-when-rendering-pr-for-the-real)

"merkledb extract-git" fetch no shard by default

---

rust/gitxetcore/src/config/xet.rs
rust/gitxetcore/src/xetblob/bbq_queries.rs
rust/gitxetcore/src/xetblob/remote_repo_info.rs

Depends on https://github.com/xetdata/xethub/pull/6117. Fix CLI-229, CLI-232.
First query `/api/xet/cas`, on failure query `api/xet/repos/...`.
Test:
1. Against Prod that doesn't have `/api/xet/cas` route yet.
```
di@di-mbp ~/tt/bsf13 % git remote -v
origin	https://seanses:[masked]@xethub.com/seanses/bsf13 (fetch)
origin	https://seanses:[masked]@xethub.com/seanses/bsf13 (push)
di@di-mbp ~/tt/bsf13 % XET_LOG_LEVEL=debug git xet cas probe d760aaf4beb07581956e24c847c47f1abd2e419166aa68259035bc412232e9da 2>&1 | grep "Config: CAS endpoint set to:"
{"timestamp":"2024-06-07T22:01:32.919316Z","level":"DEBUG","fields":{"message":"Config: CAS endpoint set to: cas-lb.xethub.com:443"},"filename":"/Users/di/xetdata/xet-core/rust/gitxetcore/src/config/xet.rs","line_number":301,"span":{"command":"cas.pro …
```

cas endpoint query without auth

---

libxet/Cargo.lock
rust/gitxetcore/src/xetblob/rfile_object.rs
rust/progress_reporting/src/lib.rs
rust/progress_reporting/src/writer_with_reporting.rs

This PR adds the xet-core half of the download progress reporting to the direct read-to-file path.  It also renames get(path) to read_to_path(path), which is much less confusing.  
Note: this is tested, but the testing is done with a local version of pyxet, which is up at https://github.com/xetdata/pyxet/pull/140.

Adds download progress reporting for xet. 

---

gitxet/Cargo.lock
rust/common_constants/Cargo.toml
rust/common_constants/src/lib.rs
rust/gitxetcore/src/command/dematerialize.rs
rust/gitxetcore/src/command/materialize.rs
rust/gitxetcore/src/data/cas_interface.rs
rust/gitxetcore/src/data/data_processing_v1.rs
rust/gitxetcore/src/data/data_processing_v2.rs
rust/gitxetcore/src/data/mdb.rs
rust/gitxetcore/src/git_integration/git_xet_repo.rs
rust/gitxetcore/src/xetblob/xet_repo.rs

Fix CLI-221
- lower default concurrent upload/download to 8
- provide env var to reset the default

Lower the number of default concurrent upload/download

---

rust/gitxetcore/src/xetblob/bbq_queries.rs

When the xet api query response statuscode is 403, return the message in the response. Fix FUN-90

Return message on query response of forbidden status

---

gitxet/Cargo.lock
libxet/Cargo.lock
rust/gitxetcore/Cargo.toml
rust/gitxetcore/src/command/repo.rs

So it turns out that canonicalize() is broken on windows in the sense that a canonicalized path can no longer be treated as a linux based path due to //?/ being prepended to it.  This fixes this issue.

Fix for windows integration test issues.

---

.github/workflows/commit.yml
gitxet/Cargo.lock
rust/Cargo.toml
scripts/ready-pull-request.sh

cargo fmt sometimes has false positives, which is annoying for getting PRs submitted!   This relaxes the requirements a bit.

Relax the scripts checking cargo fmt requirements.
