xetdata/xet-core

- rust/gitxet/tests/integration_tests/test_dir_summaries.sh
Caused by #58 -- did not run tests before merging.
> Fix test break

- rust/gitxetcore/src/config/xet.rs
Dedupe the identified set of configurations.
> Allow multiple remotes

- rust/gitxetcore/src/command/dir_summary.rs
- rust/gitxetcore/src/command/summary.rs
- rust/gitxetcore/src/diff.rs
- rust/gitxetcore/src/diff/fetcher.rs
- rust/gitxetcore/src/summaries/analysis.rs
There are no actual code changes here; this PR simply comes from running `cargo fmt` on the code base and committing the changes.
> Added format corrections to unformatted files.

- rust/gitxetcore/src/xetmnt/mod.rs
Only when the mount path was created by `xet mount`
> Delete mount path on unmount

- rust/xetblob/src/wfile_object.rs
Fix https://github.com/xetdata/xethub/issues/3544
> Xetblob bound channel

- rust/gitxetcore/src/data_processing_v2.rs
- rust/xetblob/src/xet_repo.rs
Needed for https://github.com/xetdata/pyxet/pull/27.  Fixes some issues with the shard hint downloading.
> Fixed some issues with shard hint downloading.

- rust/mdb_shard/src/shard_file_manager.rs
Hash querying gets very verbose in debug mode; this changes some things to trace now that we're confident in the MDBV2 system.
> Dropped some debug statements to trace.

- rust/gitxetcore/src/config/xet.rs
`XET_NO_SMUDGE` pollutes the config parsing from Env. This checks for env var `XET_NO_SMUDGE` and tries to remove it before parsing. See more context [here](https://github.com/xetdata/xethub/issues/3645#issuecomment-1659400324).
Fix https://github.com/xetdata/xethub/issues/3645.
> Precheck and remove XET_NO_SMUDGE

- rust/xetblob/src/lib.rs
Allow for better backward compatibility
> Made the lastmodified flag optional during JSON parsing

- rust/xetblob/src/bbq_queries.rs
The previous fix https://github.com/xetdata/xet-core/pull/102 is incomplete. Suppose directory tt contains
```
tt
--aa
--data0
--data1
--bb
--data
```
, and then execute
`xet cp -r tt xet://user/repo/main`, which will query bbq `user/repo/main` first. On commit `tt/aa/data0`, invalidating the cache entry for `tt/aa/data0` and its parent `tt/aa` is not enough --- we need to invalidate all its ancestors.
> invalidates bbq cache for all ancestors

- rust/gitxetcore/src/axe.rs
- Similar to https://github.com/xetdata/xethub/pull/4055 but for git-xet client
> Update email property name in AXE

- rust/shard_client/src/shard_client.rs
- rust/utils/proto/shard.proto
Adds in an optional force field to the shard sync request to allow forced updates of the database.
> Update to shard sync protocol.

- rust/xetblob/src/bbq_queries.rs
- rust/xetblob/src/xet_repo_manager.rs
Context: https://docs.gitlab.com/ee/user/project/repository/index.html#what-happens-when-a-repository-path-changes
> Fix for rename issue

- rust/gitxetcore/src/command/merkledb.rs
This PR adds an option "merkledb version --with-salt" to print repo salt, if present, along with MDB version. Required by xetea returning repo info.
> print repo salt along with mdb version

- rust/parutils/src/parallel_utils.rs
For limited use; needed for a specific point in git integration. 
May not work well with the futures stream library.
> Allow (limited) calling of async functions from non async code.

- rust/gitxetcore/src/upgrade_checks.rs
No logic change, just had the info!("...") statements wrong in one section.
> Correct wrong info statement in upgrade check.

- rust/gitxetcore/src/command/mount.rs
Fix https://github.com/xetdata/xethub/issues/4140
> hide "Cloning into temporary directory"

- rust/cas_client/src/local_client.rs
- rust/gitxetcore/src/async_file_iterator.rs
- rust/gitxetcore/src/command/dir_summary.rs
- rust/gitxetcore/src/git_integration/git_commits.rs
- rust/gitxetcore/src/summaries_plumb.rs
- rust/progress_reporting/src/data_progress.rs
- rust/xetblob/src/bin/xetcmd.rs
Unfortunately, there were files checked in to the repo without properly running cargo fmt on them.   This PR is simply the result of running cargo fmt.  There are no functional changes.
> Run Cargo fmt on repo

- rust/gitxetcore/Cargo.toml
- rust/xetblob/Cargo.toml
Use native certs on other operating systems, and embedded root certs on MacOS
> Make use of webpki-roots conditional on operating system

- rust/gitxetcore/src/summaries/csv.rs
Currently, the csv analyzer ignores the last line if there isn't a newline character at the end of that line.  This fixes that.
> Fix for csv parsing skipping last line on EOF

- rust/gitxet/tests/integration_tests/test_xet_lazy.sh
- rust/gitxetcore/src/command/dematerialize.rs
- rust/gitxetcore/src/command/materialize.rs
Fix https://github.com/xetdata/xethub/issues/4781
> (de)materialize accepts multiple paths

- README.md
The current readme doesn't function as any real sort of a landing page.  This provides a simple update to give more context and connections to the rest of our content.
> Update to README 

- rust/gitxet/tests/integration_tests/test_stored_notes.sh
Simple fix for the ultra slow test_stored_notes test.
> Fix for ultra slow test_stored_notes test. 

- rust/gitxetcore/src/config/authentication.rs
- rust/gitxetcore/src/config/user.rs
Also user_id should prioritize https instead of ssh.
> SSH login should check for exit code

- rust/cache/Cargo.toml
- rust/cas_client/Cargo.toml
- rust/gitxet/Cargo.toml
- rust/gitxetcore/Cargo.toml
- rust/lazy/Cargo.toml
- rust/mdb_shard/Cargo.toml
- rust/merkledb/Cargo.toml
- rust/parutils/Cargo.toml
- rust/progress_reporting/Cargo.toml
- rust/retry_strategy/Cargo.toml
- rust/shard_client/Cargo.toml
- rust/utils/Cargo.toml
- rust/xetblob/Cargo.toml
Version 1.36 is needed for some features now.
> Upgraded tokio version.

- rust/cache/src/disk/storage.rs
- rust/cas_client/src/caching_client.rs
- rust/cas_client/src/cas_connection_pool.rs
- rust/cas_client/src/data_transport.rs
- rust/cas_client/src/grpc.rs
- rust/cas_client/src/remote_client.rs
- rust/gitxetcore/src/config/cas.rs
- rust/gitxetcore/src/config/log.rs
- rust/gitxetcore/src/diff/fetcher.rs
- rust/gitxetcore/src/environment/upgrade_checks.rs
- rust/gitxetcore/src/summaries/csv.rs
- rust/gitxetcore/src/summaries/summary_type.rs
- rust/gitxetcore/src/xetmnt/watch/metadata.rs
- rust/gitxetcore/src/xetmnt/watch/metadata/filesystem.rs
- rust/xet_config/src/cfg.rs
This PR only updates the formatting by running cargo fmt.  It has no content changes.
> The result of running cargo fmt.

- .github/workflows/commit.yml
- rust/gitxetcore/Cargo.toml
> Upgrade make -- will this help the openssl issue?

- rust/gitxetcore/src/xetblob/xet_repo_manager.rs
> Added in shallow clone for repo manager.

- rust/gitxetcore/src/xetblob/mod.rs
Expose BbqClient for external crates.
> pub use BbqClient

- rust/utils/src/compression.rs
> CompressionScheme additional functionality

- rust/gitxetcore/src/command/login.rs
- Missed a config path when hostname is specified in --login
- awscli needs protocol for endpoint
> some s3 login fixes

- rust/gitxetcore/Cargo.toml
- rust/gitxetcore/src/command/mod.rs
Possible fix for https://github.com/xetdata/xet-tools/issues/45
> Possible fix for connection issues.

- gitxet/Cargo.lock
- rust/gitxetcore/Cargo.toml
Adds https support back in to git2
> Allow git2 to use https.

- gitxet/Cargo.lock
- rust/gitxetcore/src/stream/data_iterators.rs
- rust/gitxetcore/src/stream/mod.rs
- rust/gitxetcore/src/stream/stdout_process_stream.rs
- rust/parutils/src/async_iterator.rs
Adds an AsyncDataIterator implementation that streams data chunks from the stdout of an external process.  This allows the stdout of a `git lfs smudge` or `git xet smudge` command to be streamed directly into our data ingestion commands.
> Added streaming process to form a data iterator from stdout.

- rust/gitxetcore/src/command/mod.rs
Fixing the clap config in #342
> Removing hidden clap commands

- gitxet/Cargo.lock
- gitxet/Cargo.toml
- libxet/Cargo.toml
- rust/cache/Cargo.toml
- rust/cas_client/Cargo.toml
- rust/chunkpipe/Cargo.toml
- rust/common_constants/Cargo.toml
- rust/data_analysis/Cargo.toml
- rust/error_printer/Cargo.toml
- rust/gitxetcore/Cargo.toml
- rust/lazy/Cargo.toml
- rust/libmagic/Cargo.toml
- rust/mdb_shard/Cargo.toml
- rust/merkledb/Cargo.toml
- rust/merklehash/Cargo.toml
- rust/parutils/Cargo.toml
- rust/pointer_file/Cargo.toml
- rust/progress_reporting/Cargo.toml
- rust/prometheus_dict_encoder/Cargo.toml
- rust/retry_strategy/Cargo.toml
- rust/shard_client/Cargo.toml
- rust/tableau_summary/Cargo.toml
- rust/utils/Cargo.toml
- rust/xet_config/Cargo.toml
- rust/xet_error/Cargo.toml
- rust/xetblob/Cargo.toml
> Pre-release: updating version to 0.14.0

- gitxet/tests/integration_tests/initialize.sh
- gitxet/tests/upgrade_consistency_tests/setup_run_environment.sh
- libxet/Cargo.lock
As a security measure, hooks can be problematic.  This prevents this.
> Fix for build break involving new git version. 

- libxet/Cargo.lock
libxet didn't get the memo about the version update.
> Update cargo lock in libxet.

- rust/cas_client/src/staging_client.rs
This PR adds the ability to bypass staging during git xet repo migrate, uploading new data to CAS directly. 
To use this, run with `XET_CAS_BYPASS_STAGING=1`
```
XET_CAS_BYPASS_STAGING=1 git xet repo migrate
```
> Add ability to bypass staging during git xet repo migrate.

- rust/gitxetcore/src/git_integration/git_xet_repo.rs
> wait for Xorb upload to finish before uploading & sync any shard

- rust/gitxetcore/src/git_integration/repo_migration/migration.rs
So turns out that pull requests are stored as references, which should not be migrated.   The previous PR had all references treated together, which isn't what we want when there are open PRs.  This fixes that.
> Exclude pull requests from migrated references. 

- xetldfs/src/bin/xcmd.rs
- xetldfs/src/lib.rs
- xetldfs/tests/integration_tests.rs
- xetldfs/tests/integration_tests/setup_test_pyenv.sh
- xetldfs/tests/integration_tests/setup_test_repo.sh
- xetldfs/tests/integration_tests/test_python.sh
- Add some python tests, resolves some of CLI-266.
- Fix open-seek-tell to get file size on Linux, fixes CLI-276
> xetldfs python tests
